timezone: America/Los_Angeles
encoding: utf-8

author: Shane
site_name: PlayDrift Extension
site_url: https://playdrift-extension.cssnr.com

github_name: cssnr/playdrift-extension
github_url: https://github.com/cssnr/playdrift-extension

chrome_id: anlkpnbhiiojmedlkchcdmigkdccnmcn
chrome_url: https://chromewebstore.google.com/detail/playdrift-extension/anlkpnbhiiojmedlkchcdmigkdccnmcn

firefox_id: playdrift-extension
firefox_url: https://addons.mozilla.org/addon/playdrift-extension

discord_webhook: https://discord.com/api/webhooks/242137648028712961/4xM7SXClH_i8we_epG6AXMaqhueg5L5oAVf1dnLw1_el05OxZ-JVfph-QrcQwPkOMJem
