timezone: America/Los_Angeles
encoding: utf-8

url: https://playdrift-extension.cssnr.com

author: Shane
site_name: PlayDrift Extension

menu:
    - name: Home
      link: /
    - name: Docs
      link: /docs/
    - name: Screen Shots
      link: /screenshots/
      external: true

github_name: cssnr/playdrift-extension
github_url: https://github.com/cssnr/playdrift-extension

chrome_id: anlkpnbhiiojmedlkchcdmigkdccnmcn
chrome_url: https://chromewebstore.google.com/detail/playdrift-extension/anlkpnbhiiojmedlkchcdmigkdccnmcn

firefox_id: playdrift-extension
firefox_url: https://addons.mozilla.org/addon/playdrift-extension

discord_invite: https://discord.gg/wXy6m2X8wY
discord_webhook: https://discord.com/api/webhooks/1258944618389569566/gqge0T5UZcJHLxfAFLPNjlzsuqikQJtTlCRvVWbw2ufDv_WrJ8yzVRWenb__s1PxyawH
